Complited HW Lesson 1, MetricsManager
DavidGalamyan/LessonsASP.Net pull request #1
Opened 2021-03-23 21:51 UTC by DavidGalamyan

Здравствуйте, не знаю, насколько хорошо подобрал имена, мне кажется так любому будут понятны как методы так и переменные.

2021-03-23 21:55 UTC, DavidGalamyan commented
Василий помог, сначала начал изобретать велосипед (в голову не пришло, что асп может съесть не только стринг), потом были проблемы с LINQ, поскольку на курсе не проходили, а из той информации которая была, так и не понял как записать не в like-sql формате. В общем и целом сидел 2-3 дня, без Василия еще сутки бы потратил)

2021-03-24 12:32 UTC, Forkosigan requested changes

2021-03-24 12:32 UTC, Forkosigan commented on MetricsManager/MetricsManager/Controllers/CrudForWeatherForecastController.cs
> +            return BadRequest();
а почему тут BadRequest. Ведь логика, аналогичная Get вполне возможна.

2021-03-24 12:32 UTC, Forkosigan commented on MetricsManager/MetricsManager/Controllers/CrudForWeatherForecastController.cs
> +            else return BadRequest();
else лишняя. можно и без

2021-03-24 12:32 UTC, Forkosigan commented on MetricsManager/MetricsManager/Controllers/CrudForWeatherForecastController.cs
> +            catch
строить логику на Exception не надо.
лучше явно писать var itemToUpdate = _storage.SingleOrDefault(weatherForecast => weatherForecast.Date == date.Value);
if (item == null)
   return BadRequest()

2021-03-24 20:37 UTC, merged